### ISSUE TITLE
Handle shadow root

### ISSUE THREAD

**Issue by malx122** [gwwar/z-context#6]
It seems like the plugin have difficult handle web components and shadow root. Developing using Polymer and "parentStackingContext" is always "html" and not the true parent stacking context.

**Comment by gwwar** [comment]
Sorry, for the delay, I must have missed the ping. 

@malx122 I'm honestly not quite sure how z-indexes interact with the Shadow DOM, but I did add this https://github.com/gwwar/z-context/blob/56dfb6a15e566a4aca1c6c615dcd8f157b15602e/devtools/index.js#L8 a while back to prevent a JS error when inspecting shadow elements.

Is the reason here misleading, or is the behavior unexpected? To fix the latter, I'll probably need help looking up the related spec or seeing a few examples.

**Comment by edenilan** [comment]
There is no mention of "stacking context" or "z-index" in the [w3 spec for "CSS Scoping"](https://www.w3.org/TR/css-scoping-1/) (which defines the shadow DOM behavior).
There's also no mention of shadow DOM in the [z-index spec](https://www.w3.org/TR/CSS2/zindex.html).

This "lack" of documentation implies that the stacking context of elements should not be affected by whether or not they live inside a ShadowRoot.
So with regards to z-index and stacking context, you can think of the Shadow host as a native html element which allows content to be projected into it (e.g. html `<form>` element).

This is also the behavior I'm observing in the current browser implementations.

I opened a PR with a small fix for this: [https://github.com/gwwar/z-context/pull/17](https://github.com/gwwar/z-context/pull/17)

**Comment by gwwar** [comment]
Closed by @edenilan in #17 

If there are other corner cases, let's add a new issue for it 👍
